spring.datasource.url=jdbc:postgresql://localhost:5432/visa2
spring.datasource.username=cindy
spring.datasource.password=cindy2301

spring.jpa.hibernate.ddl-auto=update

# Initialisation des données SQL
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# File Upload Configuration
app.upload.dir=./uploads
app.upload.max-file-size=10MB
app.upload.max-files-per-demande=10
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
