spring.datasource.url=jdbc:postgresql://localhost:5432/visa
spring.datasource.username=cindy
spring.datasource.password=cindy2301

spring.jpa.hibernate.ddl-auto=update

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
